server:
 port: ${PORT:8080}
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:test


logging:
  level:
    org:
      springframework:
        web: DEBUG


jwt:
  auth:
    app: Spring-Security-App
    secret_key: testkey#secret@12334
    expires_in: 3600