server:
 port: ${PORT:8080}
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
     ddl-auto: validate
    properties:
      hibernate:
        default_schema: wizard
  datasource:
    url: jdbc:postgresql://ec2-34-193-112-164.compute-1.amazonaws.com:5432/d3nh4fia1c7qgq
    username: amygbmsolcjzdj
    password: d2b8eacd265629f322dedc77d0f3b6e13e721712df9cfb1e2b58a1506dcc7e82
    hikari:
      schema: wizard
    driver-class-name: org.postgresql.Driver
  flyway:
    user: amygbmsolcjzdj
    password: d2b8eacd265629f322dedc77d0f3b6e13e721712df9cfb1e2b58a1506dcc7e82
    schemas: wizard
    url: jdbc:postgresql://ec2-34-193-112-164.compute-1.amazonaws.com:5432/d3nh4fia1c7qgq
    enabled: true
    locations: classpath:db

logging:
  level:
    root:
      INFO
    org:
      springframework:
        web: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE

jwt:
  auth:
    app: Spring-Security-App
    secret_key: testkey#secret@12334
    expires_in: 10800
