server:
 port: ${PORT:8080}
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
     ddl-auto: validate
    properties:
      hibernate:
        default_schema: wizard
  datasource:
    url: jdbc:postgresql://localhost:5440/wizard
    username: migration
    password: 123456
    driver-class-name: org.postgresql.Driver


logging:
  level:
    org:
      springframework:
        web: DEBUG


jwt:
  auth:
    app: Spring-Security-App
    secret_key: testkey#secret@12334
    expires_in: 3600