openapi: 3.0.1
info:
  title: player-crud
  description: 'проект - это проект для работы с сущностью player'
  license:
    name: MIT open source license
  version: 0.0.1
servers:
  - url: https://localhost/
tags:
  - name: player-crud
    description: CRUDS для player
  - name: player
    description: создание, обновление, чтение, удаление и поиск игроков мафии
paths:
  /player/create:
    post:
      tags:
        - player
      summary: создать юнита
      operationId: createPLayer
      requestBody:
        description: Объект запроса для создания юнита
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePlayerRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePlayerResponse'

  /player/read:
    post:
      tags:
        - player
      summary: Получить информацию о юните
      operationId: readPlayer
      requestBody:
        description: Объект запроса для получения информации о юните
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadPlayerRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadPlayerResponse'
  /player/update:
    post:
      tags:
        - player
      summary: Обновить юнита
      operationId: updatePlayer
      requestBody:
        description: Объект запроса для обновления игрока
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePlayerRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdatePlayerResponse'
  /player/delete:
    post:
      tags:
        - player
      summary: Удалить юнита
      operationId: deletePlayer
      requestBody:
        description: Объект запроса для удаления юнита
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeletePlayerRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletePlayerResponse'
  /player/search:
    post:
      tags:
        - player
      summary: Поиск юнитов
      operationId: searchAd
      requestBody:
        description: Объект запроса для поиска юнитов
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchPlayerRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchPlayerResponse'

components:
  schemas:


    CreatePlayerRequest:
      description: Структура для создания юнита в репоизтории
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseRequest'
        - $ref: '#/components/schemas/PlayerMetaInfo'



    CreatePlayerResponse:
      description: Структура для ответа после создания юнита
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseResponse'
        - type: object


    ReadPlayerRequest:
      description: Структура для получения юнита
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseRequest'
        - type: object
          required:
            - messageUUID
          properties:
            playerUuid:
              type: string
              format: uuid
            debug:
              allOf:
                - $ref: 'common.yaml#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyId
                        - databaseError
    ReadPlayerResponse:
      description: Структура для ответа на запрос с информацией о юните
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseResponse'
        - $ref: '#/components/schemas/PlayerMetaInfo'
        - type: object
          properties:
            payload:
              type: string

    UpdatePlayerRequest:
      description: Структура для запроса обновления существующего юнита
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseRequest'
        - $ref: 'common.yaml#/components/schemas/BaseResponse'
        - $ref: '#/components/schemas/PlayerMetaInfo'

    UpdatePlayerResponse:
      description: Структура для ответа на запрос с информацией о юните
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseResponse'
        - type: object

    DeletePlayerRequest:
      description: Структура для запроса удаления юнита
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseRequest'
        - type: object
          properties:
            playerUuid:
              type: string
              format: uuid
            debug:
              allOf:
                - $ref: 'common.yaml#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyId
                        - databaseError



    DeletePlayerResponse:
      description: Структура для ответа на запрос об удалении юнита
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            payload:
              type: string

    SearchPlayerRequest:
      description: Структура для запроса поиска юнитов
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseRequest'
        - type: object
          properties:
            page:
              $ref: 'common.yaml#/components/schemas/BasePaginatedRequest'

    PlayerMetaInfo:
      description: мета-инфомация для юнита
      allOf:
        - $ref: '#/components/schemas/GamePlayerInfo'
        - type: object
          properties:
            ratingId:
              description: Порядковый номер в рейтинге
              type: integer
            victoriesPercent:
              description: процент побед
              type: integer
            victories:
              description: количестdо побед
              type: integer
            victoriesRedPercent:
              description: процент побед за красных
              type: integer
            victoriesBlackPercent:
              description: процент побед за черных
              type: integer
            games:
              description: игр всего сыграно
              type: integer
            rating:
              description: Итоговый рейтинг (процент побед умножить на сумму баллов)
              type: number
              format: double
            created:
              description: когда создан?
              type: string
              format: date-time
            updated:
              description: когда был обновлен?
              type: string
              format: date-time

    GamePlayerInfo:
      description: мета-инфомация для юнита, которая не используется в статистике
      type: object
      properties:
        playerUuid:
          description: идентификатор юнита
          type: string
          format: uuid
        nickName:
          description: имя юнита
          type: string
        foulAmount:
          description: количество фолов
          type: integer
        points:
          description: Сумма баллов
          type: integer
        additionalPoints:
          description: additionalPoints
          type: integer
        penalties:
          description: Штрафные баллы (сумма)
          type: integer
        bestMove:
          description: Лучший ход я(сумма)
          type: integer
        victoriesRed:
          description: количество побед за красных
          type: integer
        victoriesBlack:
          description: победы за черных
          type: integer
        defeatBlack:
          description: поражения за черных
          type: integer
        defeatRed:
          description: поражения за красных
          type: integer
        don:
          description: количесвто побед за дона
          type: integer
        sheriff:
          description: количество побед за шерифа
          type: integer
        wasKilled:
          description: количесвто отстрелов в первую ночь
          type: integer

    SearchPlayerResponse:
      description: Структура для ответа на запрос поиска юнитов
      allOf:
        - $ref: 'common.yaml#/components/schemas/BaseMessage'
        - $ref: 'common.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            page:
              $ref: 'common.yaml#/components/schemas/BasePaginatedResponse'
            foundMessages:
              type: array
              items:
                $ref: 'common.yaml#/components/schemas/ResponseMessage'

